# Generated by Django 3.2.13 on 2022-10-19 12:04

import baserow_enterprise.sso.oauth2.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_authenticationprovidermodel_passwordauthenticationprovidermodel'),
        ('baserow_enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAuthenticationProviderModel',
            fields=[
                ('authenticationprovidermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.authenticationprovidermodel')),
                ('name', models.CharField(blank=True, max_length=191)),
                ('client_id', models.CharField(help_text='App ID, or consumer key', max_length=191)),
                ('secret', models.CharField(blank=True, help_text='API secret, client secret, or consumer secret', max_length=191)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.authenticationprovidermodel', baserow_enterprise.sso.oauth2.models.OAuth2AuthenticationProviderMixin),
        ),
        migrations.CreateModel(
            name='GoogleAuthenticationProviderModel',
            fields=[
                ('authenticationprovidermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.authenticationprovidermodel')),
                ('name', models.CharField(blank=True, max_length=191)),
                ('client_id', models.CharField(help_text='App ID, or consumer key', max_length=191)),
                ('secret', models.CharField(blank=True, help_text='API secret, client secret, or consumer secret', max_length=191)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.authenticationprovidermodel', baserow_enterprise.sso.oauth2.models.OAuth2AuthenticationProviderMixin),
        ),
    ]
