# Generated by Django 3.2.13 on 2022-10-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baserow_enterprise', '0002_facebookauthprovidermodel_githubauthprovidermodel_gitlabauthprovidermodel_googleauthprovidermodel_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='openidconnectauthprovidermodel',
            name='access_token_url',
            field=models.URLField(default='http://example.com', help_text='URL to obtain access token'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openidconnectauthprovidermodel',
            name='authorization_url',
            field=models.URLField(default='http://example.com', help_text='URL to initiate auth flow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openidconnectauthprovidermodel',
            name='user_info_url',
            field=models.URLField(default='http://example.com', help_text='URL to get user info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facebookauthprovidermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='githubauthprovidermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gitlabauthprovidermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='googleauthprovidermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='openidconnectauthprovidermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
