# Generated by Django 3.2.13 on 2022-10-21 08:02

import baserow_enterprise.sso.oauth2.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_authenticationprovidermodel_passwordauthenticationprovidermodel'),
        ('baserow_enterprise', '0002_githubauthenticationprovidermodel_googleauthenticationprovidermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAuthenticationProviderModel',
            fields=[
                ('authenticationprovidermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.authenticationprovidermodel')),
                ('name', models.CharField(blank=True, max_length=191)),
                ('client_id', models.CharField(help_text='App ID, or consumer key', max_length=191)),
                ('secret', models.CharField(help_text='API secret, client secret, or consumer secret', max_length=191)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.authenticationprovidermodel', baserow_enterprise.sso.oauth2.models.OAuth2AuthenticationProviderMixin),
        ),
        migrations.CreateModel(
            name='GitLabAuthenticationProviderModel',
            fields=[
                ('authenticationprovidermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.authenticationprovidermodel')),
                ('name', models.CharField(blank=True, max_length=191)),
                ('url', models.URLField(help_text='Base URL of the authorization server')),
                ('client_id', models.CharField(help_text='App ID, or consumer key', max_length=191)),
                ('secret', models.CharField(help_text='API secret, client secret, or consumer secret', max_length=191)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.authenticationprovidermodel', baserow_enterprise.sso.oauth2.models.OAuth2AuthenticationProviderMixin),
        ),
        migrations.CreateModel(
            name='OpenIdConnectAuthenticationProviderModel',
            fields=[
                ('authenticationprovidermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.authenticationprovidermodel')),
                ('name', models.CharField(blank=True, max_length=191)),
                ('url', models.URLField(help_text='Base URL of the authorization server')),
                ('client_id', models.CharField(help_text='App ID, or consumer key', max_length=191)),
                ('secret', models.CharField(help_text='API secret, client secret, or consumer secret', max_length=191)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.authenticationprovidermodel', baserow_enterprise.sso.oauth2.models.OAuth2AuthenticationProviderMixin),
        ),
        migrations.AlterField(
            model_name='githubauthenticationprovidermodel',
            name='secret',
            field=models.CharField(help_text='API secret, client secret, or consumer secret', max_length=191),
        ),
        migrations.AlterField(
            model_name='googleauthenticationprovidermodel',
            name='secret',
            field=models.CharField(help_text='API secret, client secret, or consumer secret', max_length=191),
        ),
    ]
