# Generated by Django 3.2.13 on 2022-12-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_group_storage_usage_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("baserow_enterprise", "0009_roleassignment_subject_and_scope_uniqueness"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                (
                    "initial_user_id",
                    models.PositiveIntegerField(db_index=True, null=True),
                ),
                (
                    "initial_user_email",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "initial_group_id",
                    models.PositiveIntegerField(db_index=True, null=True),
                ),
                (
                    "initial_group_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "initial_application_id",
                    models.PositiveIntegerField(db_index=True, null=True),
                ),
                (
                    "initial_application_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("context_object_id", models.PositiveIntegerField(null=True)),
                ("initial_context_repr", models.CharField(max_length=255)),
                ("target_object_id", models.PositiveIntegerField(null=True)),
                ("description", models.CharField(max_length=255)),
                ("undone_at", models.DateTimeField(null=True)),
                ("redone_at", models.DateTimeField(null=True)),
                ("additional_data", models.JSONField(null=True)),
                ("from_state", models.JSONField(null=True)),
                ("to_state", models.JSONField(null=True)),
                (
                    "action",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.action",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.application",
                    ),
                ),
                (
                    "context_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_context",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.group",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_target",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
