# Generated by Django 3.2.13 on 2022-12-02 15:11

from django.db import migrations


def delete_all_team_subjects(apps, schema_editor):
    User = apps.get_model("auth", "User")
    ContentType = apps.get_model("contenttypes", "ContentType")
    TeamSubject = apps.get_model("baserow_enterprise", "TeamSubject")
    user_content_type = ContentType.objects.get_for_model(User)
    TeamSubject.objects.filter(subject_type=user_content_type).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("baserow_enterprise", "0009_roleassignment_subject_and_scope_uniqueness"),
    ]

    operations = [
        migrations.RunPython(delete_all_team_subjects, migrations.RunPython.noop),
    ]
