# Generated by Django 3.2.13 on 2022-12-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baserow_enterprise', '0011_auditlogexportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogexportjob',
            name='status',
            field=models.CharField(default='complete', help_text='The status of the export job.', max_length=32),
        ),
    ]
