# Generated by Django 3.2.13 on 2022-08-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("baserow_premium", "0005_alter_rowcomment_user"),
        ("database", "0086_collaborator_field"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollaboratorField",
            new_name="MultipleCollaboratorsField",
        ),
    ]
