# Generated by Django 3.2.13 on 2022-12-23 07:36

from django.db import migrations, models

from baserow.contrib.database.export.models import ExportJob


def forward(apps, schema_editor):
    """
    This migration will update job's state from 'complete' to 'finished' and
    multiply the progress_percentage by 100 to make them compatible with
    job that inherit from the Job class in 'core/jobs/models.py'.
    """

    ExportJob.objects.filter(state="complete").update(
        state="finished", progress_percentage=models.F("progress_percentage") * 100
    )


def reverse(apps, schema_editor):

    ExportJob.objects.filter(state="finished").update(
        state="complete", progress_percentage=models.F("progress_percentage") / 100
    )


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0093_add_auto_number_to_webhook_log"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="exportjob",
            name="database_ex_created_6af425_idx",
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="status",
            field=models.TextField(db_column="state"),
        ),
        migrations.RenameField(
            model_name="exportjob",
            old_name="status",
            new_name="state",
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["created_at", "user", "state"],
                name="database_ex_created_f04904_idx",
            ),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="state",
            field=models.TextField(
                choices=[
                    ("pending", "pending"),
                    ("exporting", "exporting"),
                    ("cancelled", "cancelled"),
                    ("finished", "finished"),
                    ("failed", "failed"),
                    ("expired", "expired"),
                ]
            ),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
