# Generated by Django 3.2.13 on 2022-07-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_default_settings_show_admin_signup_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateApplicationJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                (
                    "user_session_id",
                    models.CharField(
                        default="",
                        help_text="The user session id needed for undo/redo functionality.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user_websocket_id",
                    models.CharField(
                        default="",
                        help_text="The user websocket id needed to manage signals sent correctly.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "duplicated_application",
                    models.OneToOneField(
                        help_text="The duplicated Baserow application.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicated_from_jobs",
                        to="core.application",
                    ),
                ),
                (
                    "original_application",
                    models.ForeignKey(
                        help_text="The Baserow application to duplicate.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicated_by_jobs",
                        to="core.application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.job", models.Model),
        ),
    ]
